apiVersion: v1
kind: Pod
metadata: 
  name: aws-ebs-pod
spec: 
  
  containers: 
     - image: nginx
       name: nginx
         
       ports: 
         - containerPort: 80
           name: 'httpd-server'
       volumeMounts: 
         - mountPath: "/mnt/tmp"
           name: pv-vol
  volumes:
           - name: pv-vol
             persistentVolumeClaim: 
               claimName: claim1

              
