apiVersion: v1
kind: PersistentVolume
metadata:
        name: awsebs-pv
spec:
        capacity: 
          storage: 20Gi
        accessModes: 
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: gold


