apiVersion: v1
kind: PersistentVolume
metadata: 
   name: localpv1
spec: 
   capacity: 
     storage: 2Gi
   accessModes:
           - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: local-storage
   local: 
      path: /tmp/data
   nodeAffinity: 
      required: 
        nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
                     - ip-172-31-9-32

