apiVersion: v1
kind: Pod
metadata:
        name: nginx-app

        labels:
                app: myapp
                type: dev
        namespace: dev

spec:
   containers:
           - name: nginx
             image: nginx
