apiVersion: v1
kind: Pod
metadata:
        name: nginx-app
        namespace: app

        labels:
                app: myapp2
                type: dev

spec:
   containers:
           - name: nginx
             image: nginx
