apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deployment
        labels:
                app: nginx-deploy
spec:
        replicas: 25
        strategy:
                rollingUpdate:
                        maxSurge: 25%
                        maxUnavailable: 3
                type: RollingUpdate

        selector:
                matchLabels:
                        app: myapp
        template:
                metadata:
                        labels:
                                app: myapp
                                type: dev
                spec:
                        containers:
                                - image: coolgourav147/nginx-custom:v1
                                  name: nginx
