apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deployment
        labels:
                app: nginx-deploy
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: myapp
        template:
                metadata:
                        labels:
                                app: myapp
                spec:
                        containers:
                                - image: nginx
                                  name: nginx
