apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                type: dev
        name: nginx-deploy
spec:
        replicas: 3
        strategy:
                type: Recreate
        selector:
                matchLabels:
                        type: dev
        template:
                metadata:
                        labels:
                                type: dev
                spec:
                        containers:
                                - image: coolgourav147/nginx-custom:v2
                                  name: nginx

