apiVersion: v1
kind: Pod
metadata: 
  name: configenv
  labels: 
    type: dev
 
spec:
        containers: 
         - name: configenvpod
           image: nginx
           envFrom: 
             - configMapRef: 
                 name: emenv


