apiVersion: v1
kind: Pod
metadata:
        name: pod1
        labels:
                type: dev
spec:
        containers:
                - image: coolgourav147/nginx-custom
                  name: nginx
                  env: 
                   - name: NGINX-VALUE
                     valueFrom: 
                       configMapKeyRef: 
                         key: NAME
                         name: emenv
                               


