apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: replicaset02
        labels:
                app: replica
                env: deiv
                
spec:
        replicas: 3
        selector:
                matchExpressions:
                       - key: env
                         operator: DoesNotExist
                     
        template:
                metadata:
                        name: replicaset-pod
                spec:
                        containers:
                                - name: nginx
                                  image: nginx
