apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deploy
        labels:
                type: dev
spec:
        replicas: 2
        selector:
            matchLabels:
                     type: dev
        template:
              metadata:
                      labels:
                            type: dev
              spec:
                    containers:
                              - image: coolgourav147/nginx-custom:v1
                                name: nginx
                                resources:
                                          requests:
                                                  memory: "100Mi"
                                                  cpu: "250m"
                                          limits:
                                                  memory: "200Mi"
                                                  cpu: "500m"
