apiVersion: v1
kind: Pod
metadata:
        name: nginx-pod
        labels:
                type: dev
spec:
        containers:
                - image: coolgourav147/nginx-custom
                  name: nginx
                  resources:
                          requests:
                                  memory: 200Mi
                                  cpu: 100m

        
