apiVersion: v1
kind: ResourceQuota
metadata:
        name: quota1
        namespace: myns
spec:
        hard:
                pods: 4
                requests.cpu: 500m
                requests.memory: 500Mi
                limits.cpu: 1
                limits.memory: 1Gi
