apiVersion: v1
kind: Pod
metadata: 
   name: nginx-host-port
   namespace: default
spec: 
   containers: 
    - name: nginx
      image: nginx
      ports: 
      - hostPort: 9090
        protocol: TCP
        containerPort: 80
        
