apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
   name: nginx-ingress
spec:  
   rules: 
   - host: host.example.com
     http: 
        paths: 
         - pathType: Prefix
           path: "/"
           backend: 
             service: 
               name: nginx-deploy
               port:
                       number: 80
  

        
