apiVersion: v1
kind: Pod
metadata: 
      name: injectsecretpod
      labels: 
        type: dev
spec:
        containers:
                - name: nginx
                  image: nginx
                  env: 
                         - name: ACCESS_TOKEN
                           valueFrom:
                                 secretKeyRef:
                                     key: ACCESS_TOKEN
                                     name: envsec
 

