apiVersion: v1
kind: Pod
metadata: 
      name: secfromfile
      labels: 
        type: dev
spec:
        containers:
                - name: nginx
                  image: nginx
                  volumeMounts:
                          - mountPath: /secret
                            name: secvol
        volumes:
            - name: secvol
              secret:
                   secretName: envsec
                         
