apiVersion: v1
kind: Pod
metadata: 
      name: injectsecretpod
      labels: 
        type: dev
spec:
        containers:
                - name: nginx
                  image: nginx
                  envFrom: 
                    - secretRef:
                            name: envsec
                         
 

